services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=books_db
      - MONGO_INITDB_ROOT_USERNAME=david
      - MONGO_INITDB_ROOT_PASSWORD=1234
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=david
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=mongodb

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      # Script de inicialización
    restart: unless-stopped
    
volumes:
  postgresql_data:
  mongo: {}