spring:
  application:
    name: gateway
  kafka:
    bootstrapServers: localhost:9092
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/book/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/api/v1/borrow/**
    loadbalancer:
      clients:
        - name: book-service
          service-ids: book-service
          servers:
            - http://localhost:8083
            - http://localhost:8093
        - name: user-service
          service-ids: user-service
          servers:
            - http://localhost:8082
            - http://localhost:8092
        - name: borrow-service
          service-ids: borrow-service
          servers:
            - http://localhost:8084
            - http://localhost:8094

jwt:
  expiration: 3600000  # 1 hora en milisegundos
  refreshExpiration: 86400000  # 1 día en milisegundos